########################################################################
# concepts.R
# Copyright 2015 Geoff Evans
#
# This file is part of the Ogmap R Package.
#
# Ogmap is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ogmap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ogmap.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

#' @title Ogmap Concepts
#' @description
#' The easiest way to figure out a new package is to understand the key concepts and the problem the
#' package was designed to solve. In this case the ogmap package was created out of the desire to have a way
#' to estimate full probability distributions for a random variable of interest without resorting
#' to the standard distributional assumptions used in the standard parametric toolkit
#'
#' To better understand how ogmap works it may be worthwhile to read the following conceptual
#' documentation as needed.
#' \itemize{
#'   \item{Probability Fields:}{ \link{probField-concept}}
#'   \item{Nodes:}{ \link{nodes-concept}}
#'   \item{Internode Influence:}{ \link{influence-concept}}
#'   \item{Inference from the Field:}{ \link{inference-concept}}
#'   \item{Field Correctness:}{ \link{correctness-concept}}
#' }
#' @name concepts
NULL

#' @title ProbField - Concept
#' @description
#' The probability field and inference derived from it are the most important concepts to
#' understand when using the ogmap package. The probability field is a function which
#' assigns a probability distribution to any point (node; see \link{nodes-concept}) within its domain.
#' The probability distributions generated by the field dictate the probability of observing any value
#' of a random variable of interest at that node.
#'
#' The probability field is built as a kernel weighted average of observations at a collection of survey nodes.
#' In essence, when the probability field is asked to assign a probability distribution to some inference node
#' it determines the distance of the inference node from all survey nodes, then assesses the probability for
#' the inference node being closest in value to each of the survey nodes. The resultant set of probabilities
#' are normalized such that the results can be taken as the probability distribution for the new node.
#' From that probability distribution function, the empirical cummulative distribution function can be calculated
#' and used to perform any distribution based statistic calculation (see \link{inference-concept}).
#'
#' The adequacy of the estimates obtained from the field depends critically on the kernel and distance
#' chosen and the parameters for those functions, see \link{correctness-concept} for more details
#' on how to ensure satisfactory parameters are chosen.
#'
#' To fit a probability field (\link{probField})
#' using the ogmap package, one first needs a \code{data.frame} containing survey nodes (or some
#' other data structure from which \link{node} can be constructed through the function \link{as.nodes}).
#' Then a  a kernel function and a distance metric are required (see \link{influence-concept}.
#' The details are roughly outlined in \link{probField} but for a gentler introduction, see the vigette
#' "gettingStarted" by running:
#'
#' \code{vignette("gettingStarted", package = "ogmap")}
#' @name probField-concept
NULL

#' @title Nodes - Concept
#' @description
#' Nodes are the data that drive both fitting and inference from a probability field (see \link{probField-concept}).
#' Nodes are a convenient container used to describe a location in covariate space (guides) and contain associated
#' information. The additional information contained in a node can include an observation of the random variable,
#' a probability distribution, and extra information used in calculating the probability distribution. The node
#' represents a point in covariate space (it need not be unique), the coordinates of this point are given
#' by the set of covariates defining its location (guides for short). Value for the guides are the only
#' necessary peice of information for a node, the contents and utility of a node is determined by the
#' type of node it is. The ogmap package recognizes two informal classes of nodes, survey nodes and inference nodes.
#' \itemize{
#' \item{Survey Nodes:}{ These nodes are the observations used to create the probability field. A survey node is
#' a member of a collection of like nodes used for constructing the probability field mapping function. The kernel
#' weighted average of these nodes is used to give distributions to the inference nodes}
#' \item{Inference Nodes:}{ These nodes are used to learn about the random variable of interest. After construction
#' these nodes are given distribution functions via the probability field, so that information about likely (or unlikely)
#' values of the random variable at each node can be obtained.}
#' }
#' @name nodes-concept
NULL

#' @title Internode Influence - Concept
#' @description
#' In order to create the probability distribution at an inference node it is necessary to determine how
#' to weight the observations at the survey nodes. This process requires a distance function and a weighting
#' function (kernel), taken together they measure the influence of the survey node on the distribution at the inference
#' node. This formalizes the intuition that the expected value of a node should be most similar to the nodes closer to it
#' in guide space. The first step is to assess how close the nodes are to one another. The distance between nodes
#' can be simple distances like euclidean distance, more complicated like spherical surface distance, or
#' even non-metric distances like string-edit or Hamming distances. The result of the distance function is then passed
#' to a kernel function which determines the weight an observation at that distance should have on the distribution.
#'
#' Serval prepared kernel and distance functions are made available by the ogmap package, although many cases may
#' require bespoke versions. Personal kernel and distance functions can be constructed through \link{distance}
#' and \link{kernel} functions.
#' @name influence-concept
NULL

#' @title Inference From the Field
#' @description
#' The point of creating a probability field is to be able to use it to perform inference. The shape this
#' inference procedure takes depends critically on the question being asked. All inference is made with respect
#' to the random variable at some set of inference nodes (see: \link{nodes-concept}). The inference can be a point
#' estimate, i.e. assessing the distribution of the random variable with respect to one or more nodes independently,
#' or the inference can be dependent on the distribution at multiple nodes (some form of weighted sum).
#'
#' Since the distribution at each inference node depends on the survey nodes used to build the field, bootstrap resampling
#' of the survey nodes allows you to place confidence limits on the estimates obtained by most inference procedures.
#' To facillitate resampling based techniques we've provided the statistic class (see \link{probFieldStatistic}).
#' Objects of this class can be used to rapidly resample a statistic of your choice.
#' @name inference-concept
NULL

#' @title Field Correctness
#' @description
#' The quality of the inference generated from a probability field is dependent on the quality (correctness)
#' of the distributions assigned by the field. If correct probability distributions
#' have been assigned then the survey observations should be uniformly distributed throughout their respective
#' distributions and nearby pairs of nodes should be independent of one another.
#'
#' How well the field satisfies these two criteria depends on the choice of kernel and distance functions
#' (see \link{influence-concept}). Once the kernel and distance functions have been chosen the shape
#' and scale parameters that govern their behaviour can be optimized to satisfy the
#' two criteria above (see \link{optimizeBandwidths}). This ensures that the distributions assigned by
#' the probability field are as correct as possible given the survey data.
#'
#' The optimization procedure hinges on knowing the probabilities that both criteria have been satisfied.
#' The probability that a survey node is uniformly distributed within its probability distributions is
#' given by the jackknife probability of that survey node. The set of these probabilities can be compared
#' to the identity line (x) with a Kolmogorov-Smirnov test. If nearby pairs of nodes are independent of
#' one-another, the difference in jackknife probabilities between each pair should be triangularly distributed,
#' which can be assessed with another Kolmogorov-Smirnov test against  \eqn{2x - x^2}.  The probabilities derived
#' from these two tests can be combined into a single optimizable quantity:.
#'
#' \deqn{product * (1 - log(product))}
#' @name correctness-concept
NULL


